version: "3"

services:
  app:
    container_name: q-scraper
    restart: always
    build: ./api
    volumes:
      - ./api:/home/node/app
    ports:
      - 3333:3333
    networks:
      - app-tier
  front: 
    container_name: front
    restart: always
    build: ./front
    command: yarn run dev
    ports: 
      - 4000:4000
    volumes: 
      - ./front:/front
      - front_node_modules:/front/node_modules
    depends_on: 
      - app 
    networks:
      - app-tier
  mongo:
    container_name: q-scraper-mongodb
    image: bitnami/mongodb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    networks:
      - app-tier
volumes: 
  front_node_modules:
networks:
  app-tier:
    driver: bridge
